apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbody
  labels:
    app: nbody
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nbody
  template:
    metadata:
      labels:
        app: nbody
    spec:
      hostIPC: true
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/tensorflow-samples/nbody
          resources:
            limits:
              # MiB
              aliyun.com/gpu-mem: 3
          name: nbody
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
            - name: CUDA_MPS_PIPE_DIRECTORY
              value: "/tmp/nvidia-mps"
            - name:  CUDA_MPS_LOG_DIRECTORY
              value:  "/tmp/nvidia-log"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
              value: "30"
          volumeMounts:
            - name: nvidia-mps
              mountPath: /tmp/nvidia-mps
        volumes:
          - name: nvidia-mps
            hostPath:
              path: /tmp/nvidia-mps

